[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'

[tool.pyright]
exclude = ['vendor']
pythonVersion = '3.11'
pythonPlatform = 'All'

reportMissingModuleSource = 'none'
reportMissingImports = 'none'
