__author__ = "AlbertUnruh"
__version__ = "0.0.0a"
__license__ = "GNU AGPLv3"
__copyright__ = f"Copyright 2023-present (c) {__author__} - Alberto-X3"
__url__ = "https://github.com/Alberto-X3/Alberto-X3-V4"
